### ISSUE TITLE
XML returned by Policy Decision API differs from documentation.

### ISSUE THREAD

**Issue by dmabtrg** [authzforce/fiware#5]
The _User and Programmer Guide_ shows the following response when using the _Policy Decision API_:

``` xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Response xmlns="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17">
   <Result>
       <Decision>Permit</Decision>
       <Status>
           <StatusCode Value="urn:oasis:names:tc:xacml:1.0:status:ok" />
       </Status>
   </Result>
</Response>
```

but when using the API with authzforce 4.4.1b, the response is:

``` xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns5:Response xmlns:ns2="http://authzforce.github.io/core/xmlns/pdp/3.6" xmlns:ns3="http://authzforce.github.io/rest-api-model/xmlns/authz/4" xmlns:ns4="http://www.w3.org/2005/Atom" xmlns:ns5="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17" xmlns:ns6="http://authzforce.github.io/pap-dao-file/xmlns/properties/3.6">
  <ns5:Result>
    <ns5:Decision>Permit</ns5:Decision>
  </ns5:Result>
</ns5:Response>
```

Is authzforce returning the wrong xml or is the documentation outdated?  All other examples in the guide use the same format that is returned by authzforce, so I assume it's the documentation that needs to be updated.

**Comment by cdanger** [comment]
These are two forms of the same XML element: `Response` in namespace `urn:oasis:names:tc:xacml:3.0:core:schema:wd-17`, which is the definition of the XACML 3.0 Response, as explained in the doc. Any XML-compliant parser will consider them the same. The first form uses the default (empty) namespace prefix for the XACML 3.0 namespace, whereas the second form uses prefix `ns5` for it. You can see from the `xmlns:ns5` attribute that this prefix is mapped to the XACML 3.0 namespace. The other namespaces do not matter as they are not used in the element here, and will be ignored by XML parsers.
There is alway a chance that the namespace prefixes you are seeing differs from the doc (for instance, it may be `ns1` instead of `ns5`) at another time or another Authzforce instance since they are allocated at runtime. What matters is the namespaces they are mapped to. In this case, the namespace prefix of the Response element is always mapped to the XACML 3.0 namespace (`urn:oasis:names:tc:xacml:3.0:core:schema:wd-17`). Anyway, if you are using a proper XML parser, you won't notice the difference. 
I will try to clarify this in the doc.

_Advice: If you are using a namespace-**unaware** parser - therefore not fully XML-compliant - that may cause you trouble with this, or if you are parsing by hand, I recommend you use a proper namespace-aware XML parser, unless you know what you are doing._
